# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - ros2
      - main

jobs:
  default:
    strategy:
      fail-fast: false
      matrix:
        env:
          - NAME: "rolling-testing-ccov"
            ROS_REPO: testing
            # TODO(tylerjw): enable coverage once there is a test
            # TARGET_CMAKE_ARGS: -DENABLE_COVERAGE=ON
            # CCOV: true
          - NAME: "rolling-main"
            ROS_REPO: main
          - NAME: "address-leak-ub-sanitizers"
            TARGET_CMAKE_ARGS: >
              -DCMAKE_BUILD_TYPE=Debug
              -DENABLE_SANITIZER_ADDRESS=ON
              -DENABLE_SANITIZER_LEAK=ON
              -DENABLE_SANITIZER_UNDEFINED_BEHAVIOR=ON
          - NAME: "thread-sanitizer-clang"
            TARGET_CMAKE_ARGS: >
              -DCMAKE_BUILD_TYPE=Debug
              -DENABLE_SANITIZER_THREAD=ON
            ADDITIONAL_DEBS: clang-10
            CC: clang-10
            CXX: clang++-10
            BEFORE_RUN_TARGET_TEST_EMBED: export ASAN_SYMBOLIZER_PATH=$(which llvm-symbolizer-10)
          - NAME: "memory-sanitizer"
            TARGET_CMAKE_ARGS: >
              -DCMAKE_BUILD_TYPE=Debug
              -DENABLE_SANITIZER_MEMORY=ON
            # TODO(tylerjw): fail on iwyu warnings
            # TODO(tylerjw): fix clang-tidy errors
          # - NAME: "static-analyzers"
          #   TARGET_CMAKE_ARGS: >
          #     -DENABLE_CLANG_TIDY=ON
          #     -DENABLE_INCLUDE_WHAT_YOU_USE=ON
          #   ADDITIONAL_DEBS: clang-tidy iwyu clang-9

    env:
      ROS_DISTRO: rolling
      # Clear the ccache stats before and log the stats after the build
      AFTER_SETUP_CCACHE: ccache --zero-stats --max-size=10.0G
      AFTER_BUILD_TARGET_WORKSPACE: ccache --show-stats
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      BASEDIR: ${{ github.workspace }}/.work

    name: ${{ matrix.env.NAME }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # The target directory cache doesn't include the source directory because
      # that comes from the checkout.  See "prepare target_ws for cache" task below
      - name: Cache target workspace
        uses: pat-s/always-upload-cache@v2.1.5
        with:
          path: ${{ env.BASEDIR }}/target_ws
          key: ${{ env.CACHE_PREFIX }}-${{ github.run_id }}
          restore-keys: ${{ env.CACHE_PREFIX }}
        env:
          CACHE_PREFIX: target_ws-${{ matrix.env.NAME }}-${{ hashFiles('**/CMakeLists.txt', '**/package.xml', '.github/workflows/ci.yaml') }}
      - name: Cache ccache
        uses: pat-s/always-upload-cache@v2.1.5
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ matrix.env.NAME }}-${{ github.sha }}-${{ github.run_id }}
          restore-keys: |
            ${{ matrix.env.NAME }}-${{ github.sha }}
            ${{ matrix.env.NAME }}
      - id: ici
        name: Run industrial_ci
        uses: ros-industrial/industrial_ci@master
        env: ${{ matrix.env }}
      - name: Upload test artifacts (on failure)
        uses: actions/upload-artifact@v2
        if: failure() && (steps.ici.outputs.run_target_test || steps.ici.outputs.target_test_results)
        with:
          name: test-results-${{ matrix.env.NAME }}
          path: ${{ env.BASEDIR }}/target_ws/**/test_results/**/*.xml
      - name: Generate codecov report
        uses: rhaschke/lcov-action@main
        if: matrix.env.CCOV && steps.ici.outputs.target_test_results == '0'
        with:
          docker: ros:rolling-ros-base-focal
          workdir: ${{ env.BASEDIR }}/target_ws
          ignore: '"*/target_ws/build/*" "*/target_ws/install/*" "*/test/*"'
      - name: Upload codecov report
        uses: codecov/codecov-action@v2
        if: matrix.env.CCOV && steps.ici.outputs.target_test_results == '0'
        with:
          files: ${{ env.BASEDIR }}/target_ws/coverage.info
      - name: Prepare target_ws for cache
        if: always()
        run: |
          du -sh ${{ env.BASEDIR }}/target_ws
          sudo find ${{ env.BASEDIR }}/target_ws -wholename '*/test_results/*' -delete
          sudo rm -rf ${{ env.BASEDIR }}/target_ws/src
          du -sh ${{ env.BASEDIR }}/target_ws
